# Site settings
title: "Waste's space"
author:
  name: Tiuna Angelini
  email: tiuna.angelini@gmail.com
description: "A personal blog for posting stuff"

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

